### ISSUE TITLE
Work Item Form One Click Actions - 

### ISSUE THREAD

**Issue by bbhatia** [mohitbagra/vsts-extensions-witoneclickactions#2]
I'd installed this extension which was helpful for the team. We are getting the loading spinner for this extension and we aren't able to use this extension any more. 

![image](https://user-images.githubusercontent.com/31042249/29325000-c1a672fa-81ab-11e7-9f73-710b5061d1d4.png)

Are there any new updates for this extension or Is there any fix for this loading spinner issue?

I'll appreciate your reply.

Thanks!

**Comment by marco-gallinari** [comment]
Plugin resources are not loading, error is that asset resources are not found (404).

![image](https://user-images.githubusercontent.com/5826601/29657463-00259246-88b8-11e7-98f9-17d31e6f59f3.png)

**Comment by mohitbagra** [comment]
My apologies. I have been inactive on github for some time. I have updated the extension and it should have fixed the issue. Can you please check if it works for you now.

**Comment by marco-gallinari** [comment]
Just checked, I confirm it's working now.
Thanks a lot!
