### ISSUE TITLE
Plugin Not Loading, I tried uninstalling and disabling as well.

### ISSUE THREAD

**Issue by isaacsuresh** [mohitbagra/vsts-extensions-witoneclickactions#3]
This plugin is not working

![oneclick not loading](https://user-images.githubusercontent.com/19312727/29421039-6a314620-8391-11e7-9944-0ffe9a767612.png)

**Comment by marco-gallinari** [comment]
Same issue happening on our vso account... duplicate of #2

**Comment by mohitbagra** [comment]
My apologies. I have been inactive on github for some time. I have updated the extension and it should have fixed the issue. Can you please check if it works for you now.

**Comment by marco-gallinari** [comment]
Just checked, I confirm it's working now.
Thanks a lot!
