### ISSUE TITLE
Add support for multiple workitem field update SetFieldValue(WI1, WI2,.....)

### ISSUE THREAD

**Issue by Siva150790** [mohitbagra/vsts-extensions-witoneclickactions#5]
In VSS.SDK  SetFieldValue() works for only ActiveWorkitem.  How to update field values for multiple workitems through VSS.SDK api. Please suggest a solution.

**Comment by mohitbagra** [comment]
Updating multiple workitems at the same time is only possible via rest api right now.
WorkItemFormService will only work with the currently opened work item in the form. Thats why it is called WorkItemFormService and not WorkItemService :)
